apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels:
    app: myapp
    tier: frontend


spec:
  template:
    metadata:
      labels:
        name: myapp-rs
        tier: frontend
    spec:
      containers:
        - name: myapp
          image: nginx
  replicas: 6        
  selector:
    matchLabels:
      tier: frontend

